person_id: person
robots: 
  - id: robot1
    default_loc: [500, 500]
  - id: robot2
    default_loc: [502, 500]
  - id: robot3
    default_loc: [504, 500]
  - id: robot4
    default_loc: [506, 500]
  - id: robot5
    default_loc: [508, 500]
  - id: robot6
    default_loc: [510, 500]
  - id: robot7
    default_loc: [512, 500]
  - id: robot8
    default_loc: [514, 500]
  - id: robot9
    default_loc: [516, 500]
  - id: robot10
    default_loc: [518, 500]
ball_id: ball
experiments:
  - prefix: tutorial
    order: 0
    experiments:
      - start_x: 6.3
        start_y: 1.15
        start_yaw: 0.0554984
        ball_x: 11.25
        ball_y: 6.8
        path:
          - id: 1
            robot: yes
          - id: 13
            robot: no
          - id: 19
            robot: yes
        extra_robots: []
        max_duration: 300 #seconds
        tutorial_duration: 30 #seconds
        is_tutorial: true
      - start_x: 27.1
        start_y: 45.5
        start_yaw: 0.0767736
        ball_x: 45.55
        ball_y: 31.05
        path:
          - id: 161
            robot: yes
          - id: 151
            robot: no
          - id: 135
            robot: yes
          - id: 127
            robot: no
          - id: 128
            robot: yes
          - id: 119
            robot: no
          - id: 114
            robot: no
          - id: 112
            robot: yes
          - id: 106
            robot: no
          - id: 109
            robot: no
        extra_robots: []
        max_duration: 300 #seconds
        tutorial_duration: 45 #seconds
        is_tutorial: true
  - prefix: control
    order: -1
    experiments:
      - start_x: 12.2
        start_y: 1.25
        start_yaw: 0
        ball_x: 26.45
        ball_y: 10.7
        path:
          - id: 3
            robot: yes
          - id: 4
            robot: no
          - id: 5
            robot: yes
          - id: 15
            robot: no
          - id: 20
            robot: no
          - id: 29
            robot: yes
          - id: 41
            robot: no
          - id: 49
            robot: no
          - id: 58
            robot: no
        extra_robots: []
        max_duration: 300 #seconds
      - start_x: 38.1
        start_y: 43.15
        start_yaw: -1.64535
        ball_x: 36.4
        ball_y: 1.3
        path:
          - id: 146
            robot: yes
          - id: 136
            robot: no
          - id: 119
            robot: no
          - id: 114
            robot: no
          - id: 112
            robot: no
          - id: 100
            robot: no
          - id: 69
            robot: no
          - id: 64
            robot: no
          - id: 55
            robot: no
          - id: 30
            robot: no
          - id: 21
            robot: no
          - id: 17
            robot: yes
          - id: 9
            robot: no
        extra_robots: []
        max_duration: 300 #seconds
      - start_x: 11.8
        start_y: 45.6
        start_yaw: 0
        ball_x: 30.8
        ball_y: 2.85
        path:
          - id: 157
            robot: yes
          - id: 149
            robot: no
          - id: 133
            robot: yes
          - id: 84
            robot: yes
          - id: 58
            robot: yes
          - id: 50
            robot: no
          - id: 42
            robot: yes
          - id: 33
            robot: no
        extra_robots:
          - loc_x: 15.4
            loc_y: 22.1
            yaw: -1.52735
          - loc_x: 24.15
            loc_y: 22.85
            yaw: -2.08039
          - loc_x: 29.55
            loc_y: 16.35
            yaw: -2.57967
          - loc_x: 19.7
            loc_y: 10.4
            yaw: -1.48014
        max_duration: 300 #seconds
  - prefix: test
    order: -1
    experiments:
      - start_x: 12.2
        start_y: 1.25
        start_yaw: 0
        ball_x: 26.45
        ball_y: 10.7
        path:
          - id: 3
            robot: yes
          - id: 4
            robot: no
          - id: 5
            robot: yes
          - id: 15
            robot: no
          - id: 20
            robot: no
          - id: 29
            robot: no
          - id: 41
            robot: no
          - id: 49
            robot: no
          - id: 50
            robot: no
          - id: 42
            robot: no
          - id: 54
            robot: no
        extra_robots: []
        max_duration: 300 #seconds
      - start_x: 38.1
        start_y: 43.15
        start_yaw: -1.64535
        ball_x: 36.4
        ball_y: 1.3
        path:
          - id: 146
            robot: yes
          - id: 136
            robot: no
          - id: 119
            robot: no
          - id: 114
            robot: no
          - id: 112
            robot: no
          - id: 100
            robot: no
          - id: 69
            robot: no
          - id: 64
            robot: no
          - id: 55
            robot: no
          - id: 30
            robot: no
          - id: 21
            robot: no
          - id: 17
            robot: yes
          - id: 9
            robot: no
        extra_robots:
          - loc_x: 45.85
            loc_y: 14.95
            yaw: -1.90286
          - loc_x: 30.4
            loc_y: 14.95
            yaw: -1.17601
        max_duration: 300 #seconds
      - start_x: 11.8
        start_y: 45.6
        start_yaw: 0
        ball_x: 30.8
        ball_y: 2.85
        path:
          - id: 157
            robot: yes
          - id: 149
            robot: no
          - id: 133
            robot: yes
          - id: 84
            robot: no
          - id: 58
            robot: no
          - id: 50
            robot: no
          - id: 42
            robot: yes
          - id: 33
            robot: no
        extra_robots: []
        max_duration: 300 #seconds
