person_id: person
robots: 
  - id: robot1
    default_loc: [500, 500]
  - id: robot2
    default_loc: [502, 500]
  - id: robot3
    default_loc: [504, 500]
  - id: robot4
    default_loc: [506, 500]
  - id: robot5
    default_loc: [508, 500]
  - id: robot6
    default_loc: [510, 500]
  - id: robot7
    default_loc: [512, 500]
  - id: robot8
    default_loc: [514, 500]
  - id: robot9
    default_loc: [516, 500]
  - id: robot10
    default_loc: [518, 500]
ball_id: ball
experiments:
  - start_x: -10.1
    start_y: 15.35
    start_yaw: -0.0499576
    ball_x: 37.9
    ball_y: 10.15
    path:
      - id: 54
        robot: yes
      - id: 61
        robot: no
      - id: 58
        robot: no
      - id: 46
        robot: yes
      - id: 39
        robot: no
      - id: 32
        robot: yes
      - id: 36
        robot: no
      - id: 37
        robot: no
      - id: 33
        robot: no
      - id: 34
        robot: yes
      - id: 27
        robot: yes
      - id: 20
        robot: no
      - id: 21
        robot: no
      - id: 12
        robot: no
      - id: 13
        robot: no
      - id: 22
        robot: no
    extra_robots:
      - loc_x: -5.55
        loc_y: 13.35
        yaw: -1.63736
      - loc_x: 15.3
        loc_y: 12.25
        yaw: -1.54139
      - loc_x: 14.75
        loc_y: 15.3
        yaw: -1.63322
    max_duration: 120 #seconds
