person_id: person
robots: 
  - id: robot1
    default_loc: [500, 500]
  - id: robot2
    default_loc: [502, 500]
  - id: robot3
    default_loc: [504, 500]
  - id: robot4
    default_loc: [506, 500]
  - id: robot5
    default_loc: [508, 500]
  - id: robot6
    default_loc: [510, 500]
  - id: robot7
    default_loc: [512, 500]
  - id: robot8
    default_loc: [514, 500]
  - id: robot9
    default_loc: [516, 500]
  - id: robot10
    default_loc: [518, 500]
ball_id: ball
experiments:
  - start_x: 3.9
    start_y: 38.05
    start_yaw: -0.174674
    ball_x: 40.6
    ball_y: 8.45
    path:
      - id: 124
        robot: yes
      - id: 93
        robot: no
      - id: 90
        robot: yes
      - id: 91
        robot: no
      - id: 92
        robot: yes
      - id: 69
        robot: no
      - id: 64
        robot: no
      - id: 55
        robot: no
      - id: 45
        robot: no
    extra_robots:
      - loc_x: 14.25
        loc_y: 27.65
        yaw: -1.5708
      - loc_x: 42.65
        loc_y: 19.6
        yaw: 2.55359
    max_duration: 120 #seconds
