person_id: person
robots: 
  - id: robot1
    default_loc: [500, 500]
  - id: robot2
    default_loc: [502, 500]
  - id: robot3
    default_loc: [504, 500]
  - id: robot4
    default_loc: [506, 500]
  - id: robot5
    default_loc: [508, 500]
  - id: robot6
    default_loc: [510, 500]
  - id: robot7
    default_loc: [512, 500]
  - id: robot8
    default_loc: [514, 500]
  - id: robot9
    default_loc: [516, 500]
  - id: robot10
    default_loc: [518, 500]
ball_id: ball
