robot_radius: 0.25
door_handler_costmap:
  global_frame: /map
  robot_base_frame: base_footprint
  publish_frequency: 1.0
  plugins:
    - name: static_layer
      type: costmap_2d::StaticLayer
    - name: door_plugin
      type: clingo_interface::CostmapDoorPlugin
    - name: obstacle_layer
      type: costmap_2d::ObstacleLayer
    - name: inflation_layer
      type: costmap_2d::InflationLayer
  obstacle_layer:
    observation_sources: scan
    scan: {data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true, expected_update_rate: 0.2, inf_is_valid: true}
  inflation_layer:
    inflation_radius: 0.3
