- corners: [[-5.05, 7.3], [-3.75, 7.25]]
  approach:
    - from: cor
      point: [-4.2, 8.1, -1.84909]
    - from: o502
      point: [-4.5, 6.5, 1.27934]
  name: d502
- corners: [[6.45, 7.35], [7.85, 7.3]]
  approach:
    - from: cor
      point: [7.3, 8.1, -1.97569]
    - from: o504
      point: [6.85, 6.3, 1.31019]
  name: d504
