- corners: [[-4.85, 7.25], [-3.75, 7.3]]
  approach:
    - from: cor
      point: [-4.3, 8.2, -1.71269]
    - from: o3_502
      point: [-4.5, 6.3, 1.41419]
  name: d3_502
- corners: [[6.6, 7.3], [7.85, 7.35]]
  approach:
    - from: cor
      point: [7.3, 8.1, -1.5708]
    - from: o3_508
      point: [7.3, 6.55, 1.5708]
  name: d3_508
