instance_groups:
  - prefix: tutorial
    instances:
      - path:
          - id: 3
            robot: yes
          - id: 4
            robot: no
          - id: 5
            robot: yes
          - id: 11
            robot: no
        robots: []
      - path:
          - id: 79
            robot: yes
          - id: 65
            robot: yes
          - id: 69
            robot: yes
          - id: 61
            robot: no
          - id: 59
            robot: yes
          - id: 56
            robot: no
          - id: 58
            robot: no
        robots: []
  - prefix: pair1
    instances:
      # instance 1 testing directional choices
      - path:
          - id: 77
            robot: yes
          - id: 78
            robot: no
          - id: 79
            robot: yes
          - id: 65
            robot: no
          - id: 57
            robot: no
          - id: 55
            robot: no
          - id: 51
            robot: no
        robots: []
      #instance 3 tests navigating a big room without directional arrows
      - path:
          - id: 39
            robot: no
          - id: 52
            robot: yes
          - id: 53
            robot: no
          - id: 68
            robot: no
          - id: 65
            robot: no
        robots: []
      #instance 5 tests distraction in presence of a robot
      - path:
          - id: 80
            robot: yes
          - id: 74
            robot: no
          - id: 61
            robot: no
          - id: 59
            robot: no
          - id: 51
            robot: yes
          - id: 33
            robot: no
          - id: 26
            robot: no
          - id: 11
            robot: no
          - id: 5
            robot: no
        robots:
          - loc_x: 30.5
            loc_y: 14.9
            yaw: -2.03444
          - loc_x: 45.8
            loc_y: 14.8
            yaw: -1.0612
  - prefix: pair2
    instances:
      # instance 2 (paired) experiment for experiment 1 in opposite direction
      - path:
          - id: 83
            robot: yes
          - id: 80
            robot: no
          - id: 79
            robot: yes
          - id: 65
            robot: no
          - id: 57
            robot: no
          - id: 54
            robot: no
          - id: 40
            robot: no
        robots: []
      #instance 4 (paired with 3) attempts to show that directions in big room help
      - path:
          - id: 39
            robot: no
          - id: 52
            robot: yes
          - id: 53
            robot: yes
          - id: 68
            robot: no
          - id: 65
            robot: no
        robots: []
      #instance 6 (paired with 5) tests distraction in absense of robot
      - path:
          - id: 80
            robot: yes
          - id: 74
            robot: no
          - id: 61
            robot: no
          - id: 59
            robot: no
          - id: 51
            robot: no
          - id: 33
            robot: no
          - id: 26
            robot: no
          - id: 11
            robot: no
          - id: 5
            robot: no
        robots:
          - loc_x: 30.5
            loc_y: 14.9
            yaw: -2.03444
          - loc_x: 45.8
            loc_y: 14.8
            yaw: -1.0612
